"""Initialise a recipebrain data directory.

Creates the directory structure and a ready-to-use ``recipebrain.toml``
config file so users can get started quickly after ``pip install recipebrain``.

Also writes a user-level pointer at ``~/.config/recipebrain/config-path``
so subsequent commands auto-discover the config without ``--config`` or
``RECIPEBRAIN_CONFIG``.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

_SUBDIRS = [
    "output",
    str(Path("dossiers") / "recipes"),
    "inbox",
    "snapshots",
]

_CONFIG_TEMPLATE = """\
# recipebrain.toml — configuration for the recipebrain CLI and MCP server
# ─────────────────────────────────────────────────────────────────────────────
# Generated by `recipebrain init`. Edit freely.
# To add secrets, create `recipebrain.local.toml` (gitignored) next to this file.

# ── Paths ──────────────────────────────────────────────────────────────────────
[paths]
output_dir = "output"
dossier_dir = "dossiers/recipes"
inbox_dir = "inbox"
snapshot_dir = "snapshots"

# ── Scraping ───────────────────────────────────────────────────────────────────
[scraping]
rate_limit_seconds = 2.0
user_agent = "recipebrain (personal use)"
respect_robots_txt = true
timeout_seconds = 30

# ── Sources ────────────────────────────────────────────────────────────────────
[sources.bettybossi]
enabled = true
language = "de"

[sources.fooby]
enabled = true
language = "de"

[sources.migusto]
enabled = true
language = "de"

# ── Promotions ─────────────────────────────────────────────────────────────────
[promotions]
enabled = true
adapter = "profital"
refresh_interval_hours = 168

# ── Pantry ─────────────────────────────────────────────────────────────────────
[pantry]
expiry_warning_days = 3

# ── MCP ────────────────────────────────────────────────────────────────────────
[mcp]
transport = "stdio"
"""


@dataclass
class InitResult:
    """Summary of what ``init_data_dir`` created."""

    root: Path
    dirs_created: list[Path]
    config_written: bool
    config_path: Path


def init_data_dir(target: Path, *, force: bool = False) -> InitResult:
    """Scaffold a recipebrain data directory at *target*.

    Creates subdirectories (``output/``, ``dossiers/recipes/``, ``inbox/``,
    ``snapshots/``) and writes a default ``recipebrain.toml``.

    Parameters
    ----------
    target:
        Directory to initialise. Created if it does not exist.
    force:
        If ``True``, overwrite an existing ``recipebrain.toml``.

    Raises
    ------
    FileExistsError
        If *target* exists but is a file (not a directory).
    FileExistsError
        If ``recipebrain.toml`` already exists and *force* is ``False``.
    """
    target = target.resolve()

    if target.exists() and not target.is_dir():
        raise FileExistsError(f"Path exists and is not a directory: {target}")

    target.mkdir(parents=True, exist_ok=True)

    dirs_created: list[Path] = []
    for sub in _SUBDIRS:
        d = target / sub
        if not d.exists():
            d.mkdir(parents=True, exist_ok=True)
            dirs_created.append(d)

    config_path = target / "recipebrain.toml"
    config_written = False

    if config_path.exists() and not force:
        raise FileExistsError(
            f"Config file already exists: {config_path}\nUse --force to overwrite."
        )

    config_path.write_text(_CONFIG_TEMPLATE, encoding="utf-8")
    config_written = True

    # Seed empty Parquet files so `doctor` and `info` see all entities
    from recipebrain.writer import seed_empty_tables, write_schema_version

    output_dir = target / "output"
    seeded = seed_empty_tables(output_dir)
    if seeded:
        write_schema_version(output_dir)
        logger.info("init: seeded %d empty Parquet files", len(seeded))

    _write_config_pointer(config_path)

    return InitResult(
        root=target,
        dirs_created=dirs_created,
        config_written=config_written,
        config_path=config_path,
    )


def _write_config_pointer(config_path: Path) -> None:
    """Write the absolute config path to ``~/.config/recipebrain/config-path``.

    Silently skips on any filesystem error (permissions, read-only home, etc.)
    so ``init`` never fails due to the pointer.
    """
    from recipebrain.settings import _CONFIG_PATH_FILE

    try:
        _CONFIG_PATH_FILE.parent.mkdir(parents=True, exist_ok=True)
        _CONFIG_PATH_FILE.write_text(str(config_path.resolve()), encoding="utf-8")
    except OSError:
        logger.debug("Could not write config pointer to %s", _CONFIG_PATH_FILE)
